module "vpc_base" {
  source                    = "../../modules/vpc"
  CIDR_BLOCK                = var.CIDR_BLOCK
  INSTANCE_TENANCY          = var.INSTANCE_TENANCY
  ENABLE_DNS_HOSTNAMES      = var.ENABLE_DNS_HOSTNAMES
  ENABLE_DNS_SUPPORT        = var.ENABLE_DNS_SUPPORT
  PUBLIC_SUBNET_CIDR_BLOCK  = var.PUBLIC_SUBNET_CIDR_BLOCK
  PRIVATE_SUBNET_CIDR_BLOCK = var.PRIVATE_SUBNET_CIDR_BLOCK
  VPC_NAME                  = var.VPC_NAME
  PUBLIC_SUBNET_NAME        = var.PUBLIC_SUBNET_NAME
  INTERNET_GATEWAY_NAME     = var.INTERNET_GATEWAY_NAME
  ROUTE_TABLE_NAME          = var.ROUTE_TABLE_NAME
#  PRIVATE_SUBNET_NAME       = var.PRIVATE_SUBNET_NAME
#yes
  AWS_REGION                = var.AWS_REGION
  APP_NAME                = var.APP_NAME
  ENVIRONMENT    = var.ENVIRONMENT
}