#instance
AWS_REGION = "eu-east-1"
INSTANCE_TYPE = ""
SECURITY_GROUP_NAME = ""
APP_NAME = ""
ENVIRONMENT = ""

#vpc
VPC_NAME = ""
PUBLIC_SUBNET_NAME = ""
PRIVATE_SUBNET_NAME = ""
NAT_GATEWAY_NAME = ""
ROUTE_TABLE_NAME = ""
INTERNET_GATEWAY_NAME = ""

#redis
ENABLE_REDIS = ""
ELASTICACHE_INSTANCE_TYPE = ""
ENGINE_VERSION = ""
REDIS_FAMILY = "

#ecr & ecs
ECR_NAME = ""
ECS_CLUSTER_NAME = ""